//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestor_De_Presupuesto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABM
    {
        public int id { get; set; }
        public string concept { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> idType { get; set; }
        public Nullable<int> operations_registered { get; set; }
    
        public virtual TYPE TYPE { get; set; }
    }
}
