//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestor_Presupuesto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class abm
    {
        public int id { get; set; }
        public string concept { get; set; }
        public int amount { get; set; }
        public System.DateTime date { get; set; }
        public int idType { get; set; }
        public int operations_registered { get; set; }
    
        public virtual dbType dbType { get; set; }
    }
}
